name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  run_infra:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: setup
        run: pwd && ls -lR
      - name: Do it 1
        uses: magnayn-mns/infradsl@master
        with:
          file: x.infra.kts  
      - name: Do it
        uses: magnayn-mns/infradsl@master
        with:
          file: script.infra.kts
